AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template is for tree instances and route-53 geo-location polcy
Parameters:

  MyhostedZone:
    Description: Seclect your hoste zone
    Type: AWS::Route53::HostedZone::Id
 
  MyKeyName:
    Description: Select your key pair
    Type: AWS::EC2::KeyPair::KeyName
    
  MyInstanceType:
    Description: Select a instance type
    Type: String
    Default: t2.micro  
    AllowedValues:
         - "t2.micro"
         - "t3.micro"
         - "t2.nano"
    
  VPC:
    Description: Select VPC 
    Type: AWS::EC2::VPC::Id

 
Resources:
  Route53NV:
    Type: AWS::Route53::RecordSet
    Properties:
      GeoLocation:
        ContinentCode: "NA"
      HostedZoneId: !Ref MyhostedZone
      Name: "*.devopsturkiye.com" # Required
      ResourceRecords: 
        - !GetAtt InstanceNV.PublicIp
      SetIdentifier: "yakin-nv-geo"
      TTL: "60"
      Type: "A" # Required

  Route53Europe:
    Type: AWS::Route53::RecordSet
    Properties:
      GeoLocation:
        ContinentCode: "EU"
      HostedZoneId: !Ref MyhostedZone
      Name: "*.devopsturkiye.com" # Required
      ResourceRecords: 
        - !GetAtt InstanceEurope.PublicIp
      SetIdentifier: "yakin-europe-geo"  
      TTL: "60"
      Type: "A" # Required

  Route53Asia:
    Type: AWS::Route53::RecordSet
    Properties:
      GeoLocation:
        ContinentCode: "AS"
      HostedZoneId: !Ref MyhostedZone
      Name: "*.devopsturkiye.com" # Required
      ResourceRecords: 
        - !GetAtt InstanceAsia.PublicIp
      SetIdentifier: "yakin-asia-geo"    
      TTL: "60"
      Type: "A" # Required


  InstanceAsia:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      ImageId: "ami-06ca3ca175f37dd66"
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroupIds:
        - !Ref InstanceSecGroup
      Tags: 
        - Key: Name
          Value: Asia
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y httpd
        yum install -y wget
        cd /var/www/html
        wget https://raw.githubusercontent.com/awsdevopsteam/route-53/master/geo-japon/index.html
        wget https://raw.githubusercontent.com/awsdevopsteam/route-53/master/geo-japon/Tsubasa.jpg
        systemctl start httpd
        systemctl enable httpd

  InstanceEurope:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      ImageId: "ami-06ca3ca175f37dd66"
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroupIds:
        - !Ref InstanceSecGroup
      Tags: 
        - Key: Name
          Value: Europe
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y httpd
        yum install -y wget
        cd /var/www/html
        wget https://raw.githubusercontent.com/awsdevopsteam/route-53/master/frankfurt/index.html
        wget https://raw.githubusercontent.com/awsdevopsteam/route-53/master/frankfurt/frankfurt.jpg
        systemctl start httpd
        systemctl enable httpd

  InstanceNV:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: "us-east-1a"
      ImageId: "ami-06ca3ca175f37dd66"
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroupIds:
        - !Ref InstanceSecGroup
      Tags: 
        - Key: Name
          Value: N-Virginya
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y httpd
        yum install -y wget
        cd /var/www/html
        wget https://raw.githubusercontent.com/awsdevopsteam/route-53/master/N.virginia_1/index.html
        wget https://raw.githubusercontent.com/awsdevopsteam/route-53/master/N.virginia_1/N.virginia_1.jpg
        systemctl start httpd
        systemctl enable httpd
 
  InstanceSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "We enabled 80 and 443 port" # Required
      GroupName: "Route53-Instance-Sec-Group"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0          
      Tags: 
        - Key: Name
          Value: HTTP-HTTPS
      VpcId: !Ref VPC

