AWSTemplateFormatVersion: 2010-09-09
Description: |
  deneme by yakin
Parameters:

  
Mappings:

Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: "5.7"
      MasterUsername: admin
      MasterUserPassword: Yakin0001
      DBInstanceIdentifier: mydbinstance
      VPCSecurityGroups:
        - !Ref MySecGrp
      AvailabilityZone: us-east-1a
      DBSubnetGroupName: mydbsubnetgroup


  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH Mysql # Required
      GroupName: yakin1
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


